Run Mono Runtime tests with wine
Signed-off-by: Zhenbo Li <litimetal@gmail.com>

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -104,6 +104,15 @@ jobs:
           wine winetest/mscoree_test.exe $testname >>winetest-output.log 2>&1 || printf '::warning mscoree:%s test failed\n' $testname
           echo END $testname TEST >>winetest-output.log
         done
+    - name: Download Wine-Mono tests
+      uses: actions/download-artifact@v2
+      with:
+        name: make tests-zip output
+    - name: Run Mono tests
+      run: |
+        unzip -q wine-mono-*-tests.zip
+        cd tests
+        wine run-tests.exe -skip-list:skip-always.txt -pass-list:wine-passing.txt -fail-list:wine-failing.txt >> ../mono_tests-wine-output.log 2>&1 || printf '::warning wine mono: test failed\n'
     - name: linux test output capture
       uses: actions/upload-artifact@v2
       with:
@@ -135,4 +144,61 @@ jobs:
           wine64 winetest64/mscoree_test.exe $testname >>winetest64-output.log 2>&1 || printf '::warning mscoree:%s test failed\n' $testname
           echo END $testname TEST >>winetest64-output.log
         done
+    - name: Download Wine-Mono tests
+      uses: actions/download-artifact@v2
+      with:
+        name: make tests-zip output
+    - name: Run Mono tests
+      run: |
+        unzip -q wine-mono-*-tests.zip
+        cd tests
+        wine64 run-tests.exe -skip-list:skip-always.txt -pass-list:wine-passing.txt -fail-list:wine-failing.txt >> ../mono_tests-wine-mac-output.log 2>&1 || printf '::warning wine-mac mono: test failed\n'
+    - name: mac test output capture
+      uses: actions/upload-artifact@v2
+      with:
+        name: mac test output
+        path: ./*.log   
+
+
+  linux-native-build:
+
+    runs-on: ubuntu-20.04
+
+    steps:
+    - uses: actions/checkout@v2
+      with:
+          submodules: recursive
+
+    - name: Remove packages require EULA
+      run: sudo apt remove msodbcsql17 linux-azure linux-cloud-tools-azure linux-headers-azure linux-image-azure linux-tools-azure -y 1>&2
+    - name: Install Mono Build Dependencies
+      run: |
+        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF 1>&2
+        echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
+        sudo apt update 1>&2
+        sudo apt-get install mono-devel mono-complete libtool-bin gettext cmake dos2unix libgdiplus zip g++ -y 1>&2
+        # Seems that Github Action Image already includes mono-devel. Still install it explicitly
+    - name: Check Environment
+      run: |
+        gcc --version 1>&2
+        g++ --version 1>&2
+        mono --version 1>&2
+        ld --version 1>&2
+        cmake --version 1>&2
+        man libtool | tail -1 1>&2
+    - name: make mono
+      run: |
+        cd mono
+        ./autogen.sh
+        make -j$(nproc)
+    - name: make mono check
+      run: |
+        cd mono
+        make check -j$(nproc) >> ../mono-native-output.log 2>&1 || printf '::warning mono native test failed\n'
+    - name: upload mono direct
+      uses: actions/upload-artifact@v2
+      with:
+        name: linux mono native test output
+        path: mono-native-output.log
+
 
